export const AUTH_REQUESTED = 'AUTH_REQUESTED';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_LOG_OUT = 'AUTH_LOG_OUT';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';
CHANGE_MODAL_TYPE
