export const AUTH_REQUESTED = 'AUTH_REQUESTED';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_LOG_OUT = 'AUTH_LOG_OUT';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';
export const CHANGE_MODAL_TYPE = 'CHANGE_MODAL_TYPE';
export const VERIFICATION_REQUEST
export const VERIFICATION_SUCCESS
export const VERIFICATION_ERROR
